version: "2"

linters:
  default: "fast"
  disable:
    - depguard
  exclusions:
    rules:
      - path: formats.go
        linters:
          - mnd
      - path: labels_test.go
        linters:
          - testpackage

formatters:
  enable:
    - gofmt
